services:
  dev:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    network_mode: host
    volumes:
      - ..:/root/workspace:delegated
    ports:
      - '3000:3000'
    command: sleep infinity